/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TreinoRouteImport } from './routes/treino'
import { Route as PesoRouteImport } from './routes/peso'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as NutricaoRouteImport } from './routes/nutricao'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TreinoAtivoRouteImport } from './routes/treino.ativo'

const TreinoRoute = TreinoRouteImport.update({
  id: '/treino',
  path: '/treino',
  getParentRoute: () => rootRouteImport,
} as any)
const PesoRoute = PesoRouteImport.update({
  id: '/peso',
  path: '/peso',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const NutricaoRoute = NutricaoRouteImport.update({
  id: '/nutricao',
  path: '/nutricao',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinoAtivoRoute = TreinoAtivoRouteImport.update({
  id: '/ativo',
  path: '/ativo',
  getParentRoute: () => TreinoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/nutricao': typeof NutricaoRoute
  '/perfil': typeof PerfilRoute
  '/peso': typeof PesoRoute
  '/treino': typeof TreinoRouteWithChildren
  '/treino/ativo': typeof TreinoAtivoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/nutricao': typeof NutricaoRoute
  '/perfil': typeof PerfilRoute
  '/peso': typeof PesoRoute
  '/treino': typeof TreinoRouteWithChildren
  '/treino/ativo': typeof TreinoAtivoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/nutricao': typeof NutricaoRoute
  '/perfil': typeof PerfilRoute
  '/peso': typeof PesoRoute
  '/treino': typeof TreinoRouteWithChildren
  '/treino/ativo': typeof TreinoAtivoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/nutricao'
    | '/perfil'
    | '/peso'
    | '/treino'
    | '/treino/ativo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/nutricao'
    | '/perfil'
    | '/peso'
    | '/treino'
    | '/treino/ativo'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/nutricao'
    | '/perfil'
    | '/peso'
    | '/treino'
    | '/treino/ativo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  NutricaoRoute: typeof NutricaoRoute
  PerfilRoute: typeof PerfilRoute
  PesoRoute: typeof PesoRoute
  TreinoRoute: typeof TreinoRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/treino': {
      id: '/treino'
      path: '/treino'
      fullPath: '/treino'
      preLoaderRoute: typeof TreinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peso': {
      id: '/peso'
      path: '/peso'
      fullPath: '/peso'
      preLoaderRoute: typeof PesoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutricao': {
      id: '/nutricao'
      path: '/nutricao'
      fullPath: '/nutricao'
      preLoaderRoute: typeof NutricaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treino/ativo': {
      id: '/treino/ativo'
      path: '/ativo'
      fullPath: '/treino/ativo'
      preLoaderRoute: typeof TreinoAtivoRouteImport
      parentRoute: typeof TreinoRoute
    }
  }
}

interface TreinoRouteChildren {
  TreinoAtivoRoute: typeof TreinoAtivoRoute
}

const TreinoRouteChildren: TreinoRouteChildren = {
  TreinoAtivoRoute: TreinoAtivoRoute,
}

const TreinoRouteWithChildren =
  TreinoRoute._addFileChildren(TreinoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  NutricaoRoute: NutricaoRoute,
  PerfilRoute: PerfilRoute,
  PesoRoute: PesoRoute,
  TreinoRoute: TreinoRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
